// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5j16ZMk5DV2J07BmWh1-Wx-51QUQyT4',
    appId: '1:107435937183:web:2bcc2974b325986a4c41aa',
    messagingSenderId: '107435937183',
    projectId: 'hamzaproject-ee564',
    authDomain: 'hamzaproject-ee564.firebaseapp.com',
    storageBucket: 'hamzaproject-ee564.appspot.com',
    measurementId: 'G-KS82MG3SYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKpmv8gc6-qHZu0NVm1QL9NMPdoNUMQyU',
    appId: '1:107435937183:android:c5e0145d99718fa94c41aa',
    messagingSenderId: '107435937183',
    projectId: 'hamzaproject-ee564',
    storageBucket: 'hamzaproject-ee564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2aNoagLq-dzPtKN7gZdemJTM6NNcEtOc',
    appId: '1:107435937183:ios:ca649b1ea1f170b94c41aa',
    messagingSenderId: '107435937183',
    projectId: 'hamzaproject-ee564',
    storageBucket: 'hamzaproject-ee564.appspot.com',
    iosClientId: '107435937183-k3pkdeks2sevvamnntb1hqdmadojm2fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2aNoagLq-dzPtKN7gZdemJTM6NNcEtOc',
    appId: '1:107435937183:ios:ca649b1ea1f170b94c41aa',
    messagingSenderId: '107435937183',
    projectId: 'hamzaproject-ee564',
    storageBucket: 'hamzaproject-ee564.appspot.com',
    iosClientId: '107435937183-k3pkdeks2sevvamnntb1hqdmadojm2fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectflutter',
  );
}
